-- EmiMatch: 30 free Likes per Argentina calendar day; Premium subscribers have unlimited Likes.
-- Count immutable like events, not the current swipe state, so toggling a swipe cannot reset the allowance.

create table if not exists public.like_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists like_events_user_created_idx
  on public.like_events (user_id, created_at desc);

alter table public.like_events enable row level security;
revoke all on table public.like_events from public, anon, authenticated;

insert into public.like_events (user_id, target_user_id, created_at)
select s.user_id, s.target_user_id, s.created_at
from public.swipes s
where s.action = 'like'
  and s.created_at >= date_trunc('day', now() at time zone 'America/Argentina/Buenos_Aires') at time zone 'America/Argentina/Buenos_Aires'
  and s.created_at < (date_trunc('day', now() at time zone 'America/Argentina/Buenos_Aires') at time zone 'America/Argentina/Buenos_Aires') + interval '1 day'
  and not exists (
    select 1 from public.like_events e
    where e.user_id=s.user_id and e.target_user_id=s.target_user_id and e.created_at=s.created_at
  );

create or replace function public.can_send_like()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_is_premium boolean;
  v_count integer := 0;
  v_limit integer := 30;
  v_day_start timestamptz :=
    date_trunc('day', now() at time zone 'America/Argentina/Buenos_Aires')
    at time zone 'America/Argentina/Buenos_Aires';
begin
  if v_user_id is null then
    return jsonb_build_object('allowed', false, 'reason', 'not_authenticated');
  end if;

  v_is_premium := coalesce(public.is_premium(), false);

  if v_is_premium then
    return jsonb_build_object(
      'allowed', true, 'is_premium', true,
      'sent', null, 'remaining', null, 'limit', null
    );
  end if;

  select count(*)::integer into v_count
  from public.like_events
  where user_id = v_user_id
    and created_at >= v_day_start
    and created_at < v_day_start + interval '1 day';

  return jsonb_build_object(
    'allowed', v_count < v_limit,
    'is_premium', false,
    'sent', v_count,
    'remaining', greatest(v_limit - v_count, 0),
    'limit', v_limit
  );
end;
$$;

revoke all on function public.can_send_like() from public, anon;
grant execute on function public.can_send_like() to authenticated;

create or replace function public.enforce_daily_like_limit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_count integer := 0;
  v_day_start timestamptz :=
    date_trunc('day', now() at time zone 'America/Argentina/Buenos_Aires')
    at time zone 'America/Argentina/Buenos_Aires';
begin
  if v_user_id is null then
    raise exception using errcode = '28000', message = 'NOT_AUTHENTICATED';
  end if;

  if new.user_id <> v_user_id then
    raise exception using errcode = '42501', message = 'SWIPE_OWNER_MISMATCH';
  end if;

  if new.action <> 'like' then
    return new;
  end if;

  if tg_op = 'UPDATE'
     and old.action = 'like'
     and new.action = 'like'
     and old.user_id = new.user_id
     and old.target_user_id = new.target_user_id then
    return new;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));

  if coalesce(public.is_premium(), false) then
    new.created_at := now();
    return new;
  end if;

  select count(*)::integer into v_count
  from public.like_events
  where user_id = v_user_id
    and created_at >= v_day_start
    and created_at < v_day_start + interval '1 day';

  if v_count >= 30 then
    raise exception using
      errcode = 'P0001',
      message = 'FREE_LIKE_LIMIT',
      detail = 'Alcanzaste el límite de 30 Me gusta gratuitos por hoy.',
      hint = 'EmiMatch Premium permite Me gusta ilimitados.';
  end if;

  insert into public.like_events (user_id, target_user_id, created_at)
  values (v_user_id, new.target_user_id, now());

  new.created_at := now();
  return new;
end;
$$;

revoke all on function public.enforce_daily_like_limit() from public, anon, authenticated;

drop trigger if exists enforce_daily_like_limit_trigger on public.swipes;
create trigger enforce_daily_like_limit_trigger
before insert or update of action on public.swipes
for each row
execute function public.enforce_daily_like_limit();
